### ISSUE TITLE
Falta afegit l'ingredient Salmó

### ISSUE THREAD

**Issue by JordiMolas** [JordiMolas/Dia2.P0_JordiM#2]
Caldria afegir un fitxar "salmó.txt" on s'expliqui com ha de ser el tall de salmó per fer el plat.

**Comment by SenseQuarter** [comment]
He tancat el pull request; pero no sembla que s'ajunti amb la branca main :-/

**Comment by JordiMolas** [comment]
Ara sí que ja tinc "els salmons" !!! 👍
